name: Create Terraform Resources

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  deploy:
    uses: Grupo-118-Tech-Challenge-Fiap-11SOAT/terraform-template-pipeline-grupo118-fase-3/.github/workflows/terraform-template-creation-resource.yml@main
    secrets: inherit